### ISSUE TITLE
How to choose rigidbody or objecttracker like Using the object_tracking_type in swarm1 

### ISSUE THREAD

**Issue by duguguang** [IMRCLab/motion_capture_tracking#22]
I want use the rigidibody raw data from motion capture system, But i found  when i wrote the marker and dynamics in the robot_types, It will aways generate the rigidbodies to the yaml. If empty, then error, It seems to the essential field. and librigidbodytracker is  always working, then output  WARN info like No updated pose for cf2 .

In fact, the pointcloud is coming from the unlabledmarkers, It has no conflict with the rigidbodies.  but what should i set the params to disable the warning info, or must i do modify the source code.

```
  px4:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: mocap_deck
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V  
```
```

[motion_capture_tracking_node-1] [WARN] [1728734491.474338487] [motion_capture_tracking]: No updated pose for cf2 for 1728734491.474086 s.
[motion_capture_tracking_node-1] [WARN] [1728734491.524861453] [motion_capture_tracking]: error: only 3 neighbors found for rigid body cf2 (need 4)
[motion_capture_tracking_node-1] [WARN] [1728734491.524925685] [motion_capture_tracking]: rigid body tracker initialization failed - check that position is correct, all markers are visible, and marker configuration matches config file
```
